<?php
$z[0]=Array("field","",87,116);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist"," \r\n        <li class=\"list-item\"> <a href=\"view.php?aid=[field:id/]\">\r\n          <div class=\"image-container\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"> </div>\r\n          <div class=\"title\">[field:title/]</div>\r\n          </a> </li>\r\n      ",197,496);
$z[1][4]=array();
$z[1][4]['titlelen']="40";
$z[1][4]['row']="8";
$z[2]=Array("field","",594,617);
$z[2][4]=array();
$z[2][4]['name']="id";

?>