
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="电子邮件" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="550" page="">
</field:content>

<field:adr itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:adr>
