<?php
$z[0]=Array("field","",102,131);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",151,182);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("arclist","\r\n                <dd><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" />\r\n                  <p>[field:title/]</p>\r\n                  <span></span> </a> </dd>\r\n                ",545,798);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="0,8";
$z[3]=Array("arclist","\r\n                <dd><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" />\r\n                  <p>[field:title/]</p>\r\n                  <span></span> </a> </dd>\r\n                ",894,1147);
$z[3][4]=array();
$z[3][4]['titlelen']="80";
$z[3][4]['orderby']="pubdate";
$z[3][4]['limit']="8,8";

?>