<?php
$z[0]=Array("field","",86,115);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist"," \r\n        <li class=\"list-item\"><a href=\"view.php?aid=[field:id/]\"><span class=\"title\">[field:title/]</span>\r\n          <time class=\"pub-date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</time>\r\n          </a></li>\r\n      ",196,474);
$z[1][4]=array();
$z[1][4]['titlelen']="40";
$z[1][4]['row']="4";
$z[2]=Array("field","",572,595);
$z[2][4]=array();
$z[2][4]['name']="id";

?>