<?php
$z[0]=Array("field","",145,174);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",217,248);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",271,299);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist"," <a class=pl href=\"[field:arcurl/]\">\r\n            <div><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></div>\r\n            <p>[field:title/]<font style=\"font:14px/1 Arial, Helvetica, sans-serif; color:#67a5ed; float:right; margin-right:10px;\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</font></p>\r\n            <span></span></a> ",679,1075);
$z[3][4]=array();
$z[3][4]['titlelen']="80";
$z[3][4]['orderby']="pubdate";

?>