<?php
$z[0]=Array("field","",152,181);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",201,232);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("sql","[field:content function='cn_substr(html2text(@me),460)'/] ",301,431);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=19";
$z[3]=Array("field","",494,522);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>