<?php
$z[0]=Array("global","",45,71);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",145,170);
$z[1][4]=array();
$z[1][4]['name']="cfg_ggtext";
$z[2]=Array("global","",1932,1954);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",2063,2087);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("type","/m/list.php?tid=[field:id/]",2192,2254);
$z[4][4]=array();
$z[4][4]['typeid']="52";

?>