<?php
$z[0]=Array("global","",122,148);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",189,215);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n      <li class=\"menuitem\"><a href=\"/m/list.php?tid={dede:field name='id'/}\">{dede:field name='typename'/}</a></li>\r\n      ",355,544);
$z[2][4]=array();
$z[2][4]['typeid']="top";
$z[2][4]['row']="9";

?>