<?php
$z[0]=Array("field","",53,82);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",102,133);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("type","\r\n        <li class=\"nknews\"><a href=\"[field:typeurl/]\"></a></li>\r\n      ",186,294);
$z[2][4]=array();
$z[2][4]['typeid']="15";
$z[3]=Array("type","\r\n        <li class=\"nkcontact\"><a href=\"[field:typeurl/]\"></a></li>\r\n      ",302,413);
$z[3][4]=array();
$z[3][4]['typeid']="19";
$z[4]=Array("type","\r\n        <li class=\"nkorder\"><a href=\"[field:typeurl/]\"></a></li>\r\n      ",421,530);
$z[4][4]=array();
$z[4][4]['typeid']="47";

?>