<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid=0 AND ispart<>2 AND ishidden<>1 AND channeltype>0  ORDER BY sortrank ASC LIMIT 20</font>
Time2017-08-05 09:21:13
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid=0 AND ispart<>2 AND ishidden<>1 AND channeltype>0  ORDER BY sortrank ASC LIMIT 20</font>
Time2017-08-05 09:21:34
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid=0 AND ispart<>2 AND ishidden<>1 AND channeltype>0  ORDER BY sortrank ASC LIMIT 20</font>
Time2017-08-05 09:22:35
*/
?>
